# Coupon Server Port
server:
  port: 9400

# Eureka Server URL
eureka:
  client:
    service-url:
      defaultZone: http://chaekmate:1234@localhost:8761/eureka

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    # HikariCP 설정 (커넥션 풀)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 5000

  jpa:
    hibernate:
      # create , update 금지
      ddl-auto: none # validate 로 수정 (전체 entity  수정 후)
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: debug # 위의 jpa: show-sql 이 true 이면 의미없음
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.amqp.rabbit.core.RabbitTemplate: debug # RabbitMQ 로깅

# Spring Boot Actuator 서버 상태(헬스) 모니터링
management:
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    db:
      enabled: true
    redis:
      enabled: true
    rabbit:
      enabled: true

# ===== RabbitMQ 설정 (Dev) =====
rabbitmq:
  member:
    exchange: dev-cm-member-fanout-exchange
    coupon-queue: dev-cm-member-signup-coupon-queue
    coupon-dlq: dev-cm-member-signup-coupon-dlq
