spring:
  application:
    name: chaekmate-coupon
  config:
    import: "optional:configserver:"    # configserver import 활성화

  cloud:
    config:
      enabled: false # Config server 사용 설정 기본 비활성화


    rabbitmq:
      host: ${RABBITMQ_HOST}
      port: ${RABBITMQ_PORT}
      username: ${RABBITMQ_USERNAME}
      password: ${RABBITMQ_PASSWORD}

    data:
      redis:
        host: ${REDIS_HOST}
        password: ${REDIS_PASSWORD}
        port: ${REDIS_PORT}
        database: ${REDIS_RANGE:304}

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: ${EUREKA_DEFAULT_URL:http://admin:1234@localhost:8761}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10


jdbc-template-batch-size: ${JDBC_BATCH_SIZE:100}

# Spring Boot Actuator 서버 상태(헬스) 모니터링
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
    redis:
      enabled: false
    rabbit:
      enabled: true
  info:
    env:
      enabled: true
info:
  instanceId: ${spring.application.name}:${server.port}
